version: '3'

services:

  # The frontend for the library.
  frontend:
    image: "nalanda_frontend"
    build: ./frontend
    environment:
      - "OPERATION_MODE=PROD"
    ports: 
      - "8080:80"
    depends_on:
      - backend
    profiles:
      - integrationTest
      - completeDeployment

  # The backend built in go.
  backend:
    image: "nalanda_backend"
    build: ./backend
    restart: always
    environment:
      - "OPERATION_MODE=PROD"
    profiles:
      - apiTest
      - integrationTest
      - completeDeployment
    depends_on:
      - database

  # This container is used for performing the migrations required for the application.
  db_migrations:
    image: "nalanda_backend_migrations"
    build: 
      context: ./backend/
      dockerfile: ./backend/migrations.Dockerfile
    profiles:
      - apiTest
      - integrationTest
      - completeDeployment
    command: go run migrations/migrate.go
    depends_on:
      - database

  # The postgres database which stores the login data for nalanda.
  database:
    image: "nalanda_database"
    build: ./database
    ports:
      - "5432:5432"
    env_file:
      - ./database/db.env
    profiles:
      - apiTest
      - integrationTest
      - completeDeployment
    #volumes:
    #  - ./database/data:/var/lib/postgresql/data